'use client'
import { useState, useRef, useEffect, Suspense } from 'react'
import { useRouter } from 'next/navigation'

const HISTORY_KEY = 'algograss_scan_history'
const MAX_HISTORY = 10

function getUser() {
  try {
    const cookies = document.cookie.split(';').map(c => c.trim())
    const cookie = cookies.find(c => c.startsWith('algograss_user='))
    if (!cookie) return null
    return JSON.parse(atob(cookie.split('=')[1]))
  } catch { return null }
}

function saveToHistory(result) {
  try {
    const prev = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]')
    const entry = { url: result.url, score: result.score, issueCount: result.issues.length, scannedAt: result.scannedAt }
    const updated = [entry, ...prev.filter(h => h.url !== result.url)].slice(0, MAX_HISTORY)
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated))
  } catch {}
}

function getHistory() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]') } catch { return [] }
}

function downloadText(text, filename) {
  const blob = new Blob([text], { type: 'text/plain' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
  URL.revokeObjectURL(a.href)
}

function buildReportText(result) {
  return [
    'ALGOGRASS COMPLIANCE REPORT',
    '===========================',
    `Website: ${result.url}`,
    `Scanned: ${new Date(result.scannedAt).toLocaleString('en-GB')}`,
    `Compliance Score: ${result.score}/100`,
    '',
    'SUMMARY',
    '-------',
    `HTTPS secure: ${result.isHttps ? 'Yes' : 'No'}`,
    `Trackers detected: ${result.trackers.length > 0 ? result.trackers.join(', ') : 'None'}`,
    `Issues found: ${result.issues.length}`,
    '',
    'ISSUES',
    '------',
    ...(result.issues.length === 0
      ? ['No issues found — well done!']
      : result.issues.map((iss, i) => `${i + 1}. [${iss.sev}] ${iss.title}\n   ${iss.desc}\n   Regulation: ${iss.reg}`)),
    '',
    'CHECKS',
    '------',
    ...Object.entries(result.checks).map(([k, v]) => `${k}: ${v ? 'PASS' : 'FAIL'}`),
    '',
    '---',
    'Generated by AlgoGrass · algograss.co.uk',
    'Expert GDPR compliance analysis by AlgoGrass AI · algograss.co.uk',
  ].join('\n')
}

function buildRoadmap(result) {
  if (!result) return []
  const steps = []
  const high = result.issues.filter(i => i.sev === 'High')
  const medium = result.issues.filter(i => i.sev === 'Medium')
  const low = result.issues.filter(i => i.sev === 'Low')
  if (high.length > 0) steps.push({ priority: 1, title: 'Fix critical issues first', desc: high.map(i => i.title).join(', '), time: '1-2 days', sev: 'High', done: false })
  if (!result.checks.privacyPolicy) steps.push({ priority: 2, title: 'Generate & publish Privacy Policy', desc: 'Use the Documents tab to generate your privacy policy, review it, then add it to your website footer.', time: '30 mins', sev: 'High', done: false })
  if (!result.checks.cookieBanner) steps.push({ priority: 3, title: 'Add a cookie consent banner', desc: 'Install a cookie management platform like CookieYes (free) or Cookiebot on your website.', time: '1 hour', sev: 'High', done: false })
  if (medium.length > 0) steps.push({ priority: 4, title: 'Address medium priority issues', desc: medium.map(i => i.title).join(', '), time: '2-3 days', sev: 'Medium', done: false })
  if (!result.checks.termsOfService) steps.push({ priority: 5, title: 'Add Terms of Service page', desc: 'Create a Terms of Service page and link it from your footer alongside the Privacy Policy.', time: '1 day', sev: 'Low', done: false })
  if (result.trackers.length > 0) steps.push({ priority: 6, title: 'Audit your tracking scripts', desc: `You have ${result.trackers.join(', ')} installed. Ensure these are only loaded after cookie consent is given.`, time: '2 hours', sev: 'Medium', done: false })
  steps.push({ priority: 7, title: 'Re-scan to verify improvements', desc: 'After making changes, run a new scan to verify your compliance score has improved.', time: '5 mins', sev: 'Info', done: false })
  return steps
}

export default function DashboardPage() {
  return <Suspense fallback={<div style={{ padding: 48, color: 'var(--ink2)' }}>Loading...</div>}><Dashboard /></Suspense>
}

function Dashboard() {
  const router = useRouter()
  const [tab, setTab] = useState('overview')
  const [scanUrl, setScanUrl] = useState('')
  const [scanning, setScanning] = useState(false)
  const [result, setResult] = useState(null)
  const [scanError, setScanError] = useState('')
  const [messages, setMessages] = useState([{ role: 'assistant', text: 'Hello! I am your AI compliance assistant. Ask me anything about GDPR, UK Data Protection Act 2018, cookie law, or data subject rights.' }])
  const [input, setInput] = useState('')
  const [aiLoading, setAiLoading] = useState(false)
  const [history, setHistory] = useState([])
  const [docState, setDocState] = useState({ privacy: null, cookie: null, dpa: null })
  const [docLoading, setDocLoading] = useState({ privacy: false, cookie: false, dpa: false })
  const [user, setUser] = useState(null)
  const [roadmapChecked, setRoadmapChecked] = useState({})
  const [emailReport, setEmailReport] = useState('')
  const [emailSent, setEmailSent] = useState(false)
  const chatRef = useRef(null)

  useEffect(() => {
    setUser(getUser())
    // Load scan history from DB, fallback to localStorage
    fetch('/api/scan-history')
      .then(r => r.json())
      .then(data => {
        if (data.scans && data.scans.length > 0) {
          const normalized = data.scans.map(s => ({
            id: s._id,
            url: s.url,
            score: s.score,
            issueCount: s.issues?.length || 0,
            scannedAt: s.scannedAt,
            fromDb: true,
          }))
          setHistory(normalized)
        } else {
          setHistory(getHistory())
        }
      })
      .catch(() => setHistory(getHistory()))

    const params = new URLSearchParams(window.location.search)
    if (params.get('upgraded') === 'true') {
      const plan = params.get('plan') || ''
      const isTrial = params.get('trial') === '1'
      const isVerified = params.get('verified') === 'true'
      const msg = isTrial
        ? `🎉 Card verified & free trial started!\n\nPlan: ${plan.charAt(0).toUpperCase()+plan.slice(1)}\n${isVerified ? '✅ The £1 verification charge has been refunded to your card.\n' : ''}You will NOT be charged for 30 days.\n\nStart exploring AlgoGrass — scan your website, generate documents, and check your GDPR compliance.`
        : `🎉 Card verified — welcome to AlgoGrass!\n\n${isVerified ? '✅ The £1 verification charge has been refunded.\n\n' : ''}Your ${plan.charAt(0).toUpperCase()+plan.slice(1)} plan is now active. Start by scanning your website below.`
      setTimeout(() => alert(msg), 500)
      window.history.replaceState({}, '', '/dashboard')
    }
  }, [])

  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight }, [messages])

  async function runScan(url) {
    const target = url || scanUrl
    if (!target.trim()) return
    setScanning(true); setScanError(''); setResult(null); setTab('overview')
    setDocState({ privacy: null, cookie: null, dpa: null })
    try {
      const res = await fetch('/api/scan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: target.trim() }) })
      const data = await res.json()
      if (data.error) { setScanError(data.error); setScanning(false); return }
      setResult(data)
      saveToHistory(data) // also save to localStorage as fallback
      // Reload history from DB
      fetch('/api/scan-history')
        .then(r => r.json())
        .then(d => {
          if (d.scans?.length > 0) {
            setHistory(d.scans.map(s => ({ id: s._id, url: s.url, score: s.score, issueCount: s.issues?.length || 0, scannedAt: s.scannedAt, fromDb: true })))
          } else {
            setHistory(getHistory())
          }
        })
        .catch(() => setHistory(getHistory()))
    } catch { setScanError('Could not connect to scanner. Please check your connection.') }
    setScanning(false)
  }

  async function generateDocument(docType) {
    if (!result) return
    setDocLoading(prev => ({ ...prev, [docType]: true }))
    try {
      const res = await fetch('/api/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ docType, scanData: result }) })
      const data = await res.json()
      if (data.error) { alert('Error: ' + data.error); return }
      setDocState(prev => ({ ...prev, [docType]: data.document }))
    } catch { alert('Failed to generate document. Please try again.') }
    setDocLoading(prev => ({ ...prev, [docType]: false }))
  }

  async function sendMessage(text) {
    const q = (text || input).trim()
    if (!q || aiLoading) return
    setInput('')
    const hist = [...messages, { role: 'user', text: q }]
    setMessages(hist); setAiLoading(true)
    try {
      const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: hist.map(m => ({ role: m.role, content: m.text })) }) })
      const data = await res.json()
      setMessages([...hist, { role: 'assistant', text: data.reply || 'Something went wrong.' }])
    } catch { setMessages([...hist, { role: 'assistant', text: 'Connection error. Please try again.' }]) }
    setAiLoading(false)
  }

  async function sendEmailReport() {
    if (!emailReport || !result) return
    try {
      await fetch(`https://formspree.io/f/${process.env.NEXT_PUBLIC_FORMSPREE_ID || 'xlgvkepp'}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: emailReport, subject: `AlgoGrass Report: ${result.url}`, report: buildReportText(result), score: result.score }),
      })
      setEmailSent(true)
    } catch { alert('Could not send email. Please download the report instead.') }
  }

  async function logout() {
    await fetch('/api/auth/logout', { method: 'POST' })
    router.push('/')
  }

  const scoreColor = result ? (result.score >= 70 ? 'var(--green)' : result.score >= 40 ? 'var(--amber-text)' : 'var(--red-text)') : 'var(--ink2)'
  const scoreLabel = result ? (result.score >= 70 ? 'Good' : result.score >= 40 ? 'Needs work' : 'At risk') : ''
  const roadmap = buildRoadmap(result)

  const tabs = [
    ['overview', 'Overview'],
    ['issues', result ? `Issues (${result.issues.length})` : 'Issues'],
    ['roadmap', 'Action Plan'],
    ['documents', 'Documents'],
    ['assistant', 'AI Assistant'],
    ['history', `History${history.length > 0 ? ` (${history.length})` : ''}`],
  ]

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      {/* Header */}
      <div style={{ background: 'var(--bg2)', padding: '18px 0', borderBottom: '1px solid var(--border)' }}>
        <div className="wrap" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}>
          <div>
            <h1 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 700, color: '#fff', marginBottom: 2 }}>
              {user ? `👋 Welcome back, ${user.name.split(' ')[0]}` : 'Compliance Dashboard'}
            </h1>
            <p style={{ fontSize: 11, color: 'rgba(255,255,255,.45)' }}>
              {result ? `${result.url} · Score: ${result.score}/100 · ${new Date(result.scannedAt).toLocaleString('en-GB')}` : 'Enter a URL to run a compliance scan'}
            </p>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            {result && (
              <button onClick={() => downloadText(buildReportText(result), `algograss-report-${result.url.replace(/[^a-z0-9]/gi, '-')}.txt`)}
                style={{ fontSize: 12, padding: '8px 14px', borderRadius: 8, border: '1px solid rgba(255,255,255,.25)', background: 'rgba(255,255,255,.1)', color: '#fff', cursor: 'pointer' }}>
                ⬇ Report
              </button>
            )}
            <form onSubmit={e => { e.preventDefault(); runScan() }} style={{ display: 'flex', gap: 8 }}>
              <input value={scanUrl} onChange={e => setScanUrl(e.target.value)} placeholder="yourwebsite.co.uk"
                style={{ background: 'rgba(255,255,255,.1)', border: '1px solid rgba(255,255,255,.2)', borderRadius: 8, padding: '8px 14px', fontSize: 13, color: '#fff', outline: 'none', width: 200 }} />
              <button type="submit" className="btn btn-primary btn-sm" disabled={scanning} style={{ minWidth: 90 }}>
                {scanning ? 'Scanning...' : '🔍 Scan'}
              </button>
            </form>
            {user && (
              <button onClick={logout} style={{ fontSize: 12, color: 'rgba(255,255,255,.5)', background: 'none', border: 'none', cursor: 'pointer' }}>Sign out</button>
            )}
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div style={{ background: 'var(--bg2)', borderBottom: '1px solid var(--border)' }}>
        <div className="wrap" style={{ display: 'flex' }}>
          {tabs.map(([id, label]) => (
            <button key={id} onClick={() => setTab(id)} className={`tab ${tab === id ? 'on' : ''}`}>{label}</button>
          ))}
          <div style={{ flex: 1 }} />
          <button onClick={() => router.push('/')} style={{ fontSize: 12, color: 'var(--ink2)', background: 'none', border: 'none', cursor: 'pointer', padding: '0 16px' }}>← Back to site</button>
        </div>
      </div>

      <div className="wrap" style={{ padding: '32px 48px' }}>
        {/* Scanning */}
        {scanning && (
          <div style={{ textAlign: 'center', padding: '64px 0' }}>
            <div style={{ width: 56, height: 56, border: '4px solid var(--green-p)', borderTop: '4px solid var(--green)', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 20px' }} />
            <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
            <p style={{ fontSize: 16, color: 'var(--ink2)', fontWeight: 300 }}>Scanning <strong style={{ color: 'var(--ink)' }}>{scanUrl}</strong>...</p>
            <p style={{ fontSize: 12, color: 'var(--ink2)', marginTop: 8 }}>Checking HTTPS, cookies, trackers, privacy policy, DSAR contact and more</p>
          </div>
        )}

        {/* Error */}
        {!scanning && scanError && (
          <div style={{ background: 'var(--red-bg)', border: '1px solid #F5B7B1', borderRadius: 14, padding: '24px 28px', maxWidth: 560 }}>
            <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 16, fontWeight: 600, color: 'var(--red-text)', marginBottom: 8 }}>Scan failed</h3>
            <p style={{ fontSize: 14, color: 'var(--red-text)', marginBottom: 16 }}>{scanError}</p>
            <button onClick={() => setScanError('')} className="btn btn-primary btn-sm">Try again</button>
          </div>
        )}

        {/* Empty state */}
        {!scanning && !scanError && !result && tab !== 'history' && (
          <div style={{ textAlign: 'center', padding: '64px 0' }}>
            <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'var(--green-p)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 32, margin: '0 auto 20px' }}>🔍</div>
            <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 22, fontWeight: 700, color: 'var(--ink)', marginBottom: 10 }}>No scan results yet</h2>
            <p style={{ fontSize: 15, color: 'var(--ink2)', marginBottom: 28, fontWeight: 300, maxWidth: 420, margin: '0 auto 28px' }}>Enter any website URL above and click Scan to get real compliance results.</p>
            <div style={{ display: 'flex', gap: 8, justifyContent: 'center', flexWrap: 'wrap' }}>
              {['bbc.co.uk', 'tesco.com', 'amazon.co.uk'].map(eg => (
                <button key={eg} onClick={() => { setScanUrl(eg); setTimeout(() => runScan(eg), 50) }}
                  style={{ fontSize: 12, padding: '7px 14px', borderRadius: 20, border: '1px solid var(--green-m)', background: 'var(--white)', color: 'var(--green)', cursor: 'pointer' }}>
                  Try {eg}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* HISTORY TAB */}
        {tab === 'history' && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
              <div>
                <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 3 }}>Scan history</h2>
                <p style={{ fontSize: 12, color: 'var(--ink2)' }}>
                  {history.length > 0 && history[0].fromDb
                    ? `${history.length} scan${history.length !== 1 ? 's' : ''} saved to your account — accessible from any device`
                    : `Your last ${MAX_HISTORY} scans stored locally`}
                </p>
              </div>
              {history.length > 0 && (
                <button onClick={() => { localStorage.removeItem(HISTORY_KEY); setHistory([]) }}
                  style={{ fontSize: 12, padding: '7px 14px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--white)', color: 'var(--ink2)', cursor: 'pointer' }}>
                  Clear local cache
                </button>
              )}
            </div>
            {history.length === 0 ? (
              <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 14, padding: 28, textAlign: 'center' }}>
                <div style={{ fontSize: 40, marginBottom: 12 }}>📋</div>
                <p style={{ fontSize: 14, color: 'var(--ink2)' }}>No scans yet. Run a scan and it will appear here.</p>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {history.map((h, i) => {
                  const col = h.score >= 70 ? 'var(--green)' : h.score >= 40 ? 'var(--amber-text)' : 'var(--red-text)'
                  return (
                    <div key={h.id || i} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 13, padding: '16px 22px', display: 'flex', alignItems: 'center', gap: 20 }}>
                      <div style={{ width: 52, height: 52, borderRadius: '50%', background: 'var(--green-p)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                        <span style={{ fontFamily: 'Syne,sans-serif', fontWeight: 800, fontSize: 16, color: col }}>{h.score}</span>
                      </div>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--ink)', marginBottom: 3 }}>{h.url}</div>
                        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                          <span style={{ fontSize: 12, color: 'var(--ink2)' }}>{h.issueCount} issue{h.issueCount !== 1 ? 's' : ''}</span>
                          <span style={{ fontSize: 12, color: 'var(--ink2)' }}>·</span>
                          <span style={{ fontSize: 12, color: 'var(--ink2)' }}>{new Date(h.scannedAt).toLocaleString('en-GB')}</span>
                          {h.fromDb && <span style={{ fontSize: 10, padding: '2px 7px', borderRadius: 4, background: 'var(--green-p)', color: 'var(--green)', fontWeight: 600 }}>☁ Saved</span>}
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: 8 }}>
                        <button onClick={() => { setScanUrl(h.url); runScan(h.url); setTab('overview') }}
                          style={{ fontSize: 12, padding: '8px 15px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500 }}>
                          Re-scan →
                        </button>
                        {h.fromDb && h.id && (
                          <button onClick={async () => {
                            await fetch('/api/scan-history', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: h.id }) })
                            setHistory(prev => prev.filter(s => s.id !== h.id))
                          }} style={{ fontSize: 12, padding: '8px 11px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--white)', color: 'var(--ink2)', cursor: 'pointer' }}>✕</button>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        )}

        {/* RESULTS TABS */}
        {!scanning && !scanError && result && tab !== 'history' && (
          <>
            {/* OVERVIEW */}
            {tab === 'overview' && (
              <>
                {/* Score hero */}
                <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 16, padding: '24px 28px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 32 }}>
                  <div style={{ position: 'relative', width: 90, height: 90, flexShrink: 0 }}>
                    <svg viewBox="0 0 100 100" width="90" height="90">
                      <circle cx="50" cy="50" r="42" fill="none" stroke="var(--green-p)" strokeWidth="10" />
                      <circle cx="50" cy="50" r="42" fill="none" stroke={scoreColor} strokeWidth="10"
                        strokeDasharray={`${result.score * 2.64} 264`} strokeLinecap="round" transform="rotate(-90 50 50)" />
                    </svg>
                    <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                      <span style={{ fontFamily: 'Syne,sans-serif', fontWeight: 800, fontSize: 20, color: scoreColor, lineHeight: 1 }}>{result.score}</span>
                      <span style={{ fontSize: 9, color: 'var(--ink2)' }}>/100</span>
                    </div>
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 20, fontWeight: 700, color: scoreColor, marginBottom: 4 }}>{scoreLabel}</div>
                    <div style={{ fontSize: 13, color: 'var(--ink2)', marginBottom: 10 }}>{result.url}</div>
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      <span style={{ fontSize: 11, padding: '3px 10px', borderRadius: 20, background: result.isHttps ? '#F0FDF4' : '#FEF2F2', color: result.isHttps ? 'var(--green)' : 'var(--red-text)', fontWeight: 500 }}>{result.isHttps ? '🔒 HTTPS' : '⚠️ No HTTPS'}</span>
                      <span style={{ fontSize: 11, padding: '3px 10px', borderRadius: 20, background: 'var(--green-p)', color: 'var(--green)', fontWeight: 500 }}>{result.issues.length} issues</span>
                      {result.trackers.length > 0 && <span style={{ fontSize: 11, padding: '3px 10px', borderRadius: 20, background: 'var(--amber-bg)', color: 'var(--amber-text)', fontWeight: 500 }}>📡 {result.trackers.join(', ')}</span>}
                    </div>
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8, flexShrink: 0 }}>
                    <button onClick={() => downloadText(buildReportText(result), `algograss-report-${result.url.replace(/[^a-z0-9]/gi, '-')}.txt`)}
                      style={{ fontSize: 12, padding: '9px 16px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500 }}>⬇ Download Report</button>
                    <button onClick={() => setTab('roadmap')}
                      style={{ fontSize: 12, padding: '9px 16px', borderRadius: 8, border: 'none', background: 'var(--green)', color: '#fff', cursor: 'pointer', fontWeight: 500 }}>📋 View Action Plan</button>
                  </div>
                </div>

                {/* Email report */}
                <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 12, padding: '14px 20px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 12 }}>
                  <span style={{ fontSize: 13, color: 'var(--ink)', fontWeight: 500, whiteSpace: 'nowrap' }}>📧 Email this report:</span>
                  {emailSent ? <span style={{ fontSize: 13, color: 'var(--green)', fontWeight: 500 }}>✅ Sent!</span> : (
                    <>
                      <input type="email" placeholder="your@email.com" value={emailReport} onChange={e => setEmailReport(e.target.value)}
                        style={{ flex: 1, border: '1px solid var(--border)', borderRadius: 8, padding: '8px 12px', fontSize: 13, outline: 'none' }} />
                      <button onClick={sendEmailReport} className="btn btn-primary btn-sm">Send →</button>
                    </>
                  )}
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 14, marginBottom: 24 }}>
                  {[
                    ['Score', result.score + '/100', scoreColor],
                    ['Issues', result.issues.length + ' found', result.issues.length > 0 ? 'var(--red-text)' : 'var(--green)'],
                    ['Trackers', result.trackers.length + ' detected', result.trackers.length > 0 ? 'var(--amber-text)' : 'var(--green)'],
                    ['HTTPS', result.isHttps ? 'Secure' : 'Not secure', result.isHttps ? 'var(--green)' : 'var(--red-text)'],
                  ].map(([label, val, col]) => (
                    <div key={label} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: '18px 16px' }}>
                      <div style={{ fontSize: 10, color: 'var(--ink2)', textTransform: 'uppercase', letterSpacing: '.08em', fontWeight: 600, marginBottom: 7 }}>{label}</div>
                      <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 26, fontWeight: 800, color: col, lineHeight: 1 }}>{val}</div>
                    </div>
                  ))}
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gap: 20 }}>
                  <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: 22 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                      <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600 }}>{result.issues.length === 0 ? '🎉 No issues!' : 'Top issues to fix'}</h3>
                      {result.issues.length > 3 && <button onClick={() => setTab('issues')} style={{ fontSize: 12, color: 'var(--green)', background: 'none', border: 'none', cursor: 'pointer' }}>View all →</button>}
                    </div>
                    {result.issues.length === 0
                      ? <p style={{ fontSize: 14, color: 'var(--green)', fontWeight: 500 }}>This website passed all compliance checks.</p>
                      : result.issues.slice(0, 4).map((iss, i) => (
                        <div key={i} style={{ display: 'flex', gap: 10, padding: '10px 0', borderBottom: '1px solid var(--green-p)', alignItems: 'flex-start' }}>
                          <span className={`chip chip-${iss.sev.toLowerCase()}`} style={{ marginTop: 2, flexShrink: 0 }}>{iss.sev}</span>
                          <div style={{ flex: 1 }}>
                            <div style={{ fontSize: 13, fontWeight: 500, color: 'var(--ink)', marginBottom: 2 }}>{iss.title}</div>
                            <div style={{ fontSize: 11, color: 'var(--ink2)' }}>{iss.reg}</div>
                          </div>
                          <button onClick={() => { setTab('assistant'); setTimeout(() => sendMessage(`How do I fix: ${iss.title}?`), 100) }}
                            style={{ fontSize: 11, padding: '5px 10px', borderRadius: 6, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', whiteSpace: 'nowrap' }}>Fix →</button>
                        </div>
                      ))}
                  </div>
                  <div style={{ background: 'var(--green)', borderRadius: 14, padding: 22 }}>
                    <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, color: '#fff', marginBottom: 14 }}>Quick actions</h3>
                    {[
                      ['View all issues', '⚠️', () => setTab('issues')],
                      ['View action plan', '📋', () => setTab('roadmap')],
                      ['Generate Privacy Policy', '📄', () => { setTab('documents'); setTimeout(() => generateDocument('privacy'), 200) }],
                      ['Generate Cookie Policy', '🍪', () => { setTab('documents'); setTimeout(() => generateDocument('cookie'), 200) }],
                      ['Generate DPA', '📋', () => { setTab('documents'); setTimeout(() => generateDocument('dpa'), 200) }],
                      ['Ask AI assistant', '🤖', () => setTab('assistant')],
                    ].map(([label, icon, action]) => (
                      <button key={label} onClick={action}
                        style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 9, padding: '9px 12px', borderRadius: 9, border: '1px solid rgba(255,255,255,.15)', background: 'rgba(255,255,255,.08)', color: '#fff', fontSize: 12, cursor: 'pointer', marginBottom: 6, textAlign: 'left' }}
                        onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,.18)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,.08)'}>
                        <span>{icon}</span>{label}
                      </button>
                    ))}
                  </div>
                </div>
              </>
            )}

            {/* ISSUES */}
            {tab === 'issues' && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                  <div><h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 3 }}>All issues — {result.url}</h2><p style={{ fontSize: 12, color: 'var(--ink2)' }}>{result.issues.length} total</p></div>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button onClick={() => setTab('roadmap')} className="btn btn-secondary btn-sm">View action plan</button>
                    <button onClick={() => setTab('assistant')} className="btn btn-primary btn-sm">Get AI help</button>
                  </div>
                </div>
                {result.issues.length === 0 ? (
                  <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 14, padding: 28, textAlign: 'center' }}>
                    <div style={{ fontSize: 40, marginBottom: 12 }}>🎉</div>
                    <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, color: 'var(--green)', marginBottom: 8 }}>No issues detected</h3>
                    <p style={{ fontSize: 14, color: 'var(--ink2)' }}>This website passed all automated compliance checks.</p>
                  </div>
                ) : (
                  <>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 20 }}>
                      {result.issues.map((iss, i) => (
                        <div key={i} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 13, padding: '18px 22px', display: 'grid', gridTemplateColumns: '80px 1fr auto', gap: 14, alignItems: 'start' }}>
                          <span className={`chip chip-${iss.sev.toLowerCase()}`} style={{ textAlign: 'center', display: 'block', padding: '4px 0', borderRadius: 6, fontSize: 11 }}>{iss.sev}</span>
                          <div>
                            <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--ink)', marginBottom: 5 }}>{iss.title}</div>
                            <div style={{ fontSize: 12, color: 'var(--ink2)', lineHeight: 1.55, marginBottom: 7 }}>{iss.desc}</div>
                            <span style={{ fontSize: 10, background: 'var(--green-p)', color: 'var(--green)', padding: '2px 8px', borderRadius: 4 }}>{iss.reg}</span>
                          </div>
                          <button onClick={() => { setTab('assistant'); setTimeout(() => sendMessage(`How do I fix: ${iss.title}? Regulation: ${iss.reg}.`), 100) }}
                            style={{ fontSize: 12, padding: '8px 14px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500, whiteSpace: 'nowrap' }}>
                            Fix with AI →
                          </button>
                        </div>
                      ))}
                    </div>
                    <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: 22 }}>
                      <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, marginBottom: 16 }}>Full check summary</h3>
                      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 2 }}>
                        {Object.entries({
                          'HTTPS encryption': result.checks.https, 'Privacy policy': result.checks.privacyPolicy,
                          'Cookie banner': result.checks.cookieBanner, 'Cookie reject option': result.checks.cookieReject,
                          'Terms of service': result.checks.termsOfService, 'Lawful basis stated': result.checks.lawfulBasis,
                          'Data subject rights': result.checks.dataRights, 'Trackers disclosed': result.checks.trackersDisclosed,
                          'Retention period': result.checks.retentionPolicy, 'DSAR contact': result.checks.dsarContact,
                          'DPO mentioned': result.checks.dpo, 'Subprocessors listed': result.checks.subprocessorsList,
                        }).map(([label, passed]) => (
                          <div key={label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 16px', background: passed ? '#F0FDF4' : '#FEF2F2', borderRadius: 8, margin: 2 }}>
                            <span style={{ fontSize: 13, color: 'var(--ink)' }}>{label}</span>
                            <span style={{ fontSize: 15 }}>{passed ? '✅' : '❌'}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </>
                )}
              </div>
            )}

            {/* ROADMAP / ACTION PLAN */}
            {tab === 'roadmap' && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                  <div>
                    <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 3 }}>Compliance Action Plan</h2>
                    <p style={{ fontSize: 12, color: 'var(--ink2)' }}>Your personalised step-by-step roadmap for {result.url}</p>
                  </div>
                  <button onClick={() => downloadText(roadmap.map((s, i) => `${i + 1}. [${s.sev}] ${s.title}\n   ${s.desc}\n   Estimated time: ${s.time}`).join('\n\n'), 'algograss-action-plan.txt')}
                    style={{ fontSize: 12, padding: '8px 14px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500 }}>
                    ⬇ Download Plan
                  </button>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  {roadmap.map((step, i) => {
                    const checked = roadmapChecked[i] || false
                    const sevColors = { High: '#FEF2F2', Medium: '#FFFBEB', Low: '#F0FDF4', Info: 'var(--green-p)' }
                    const sevTextColors = { High: 'var(--red-text)', Medium: 'var(--amber-text)', Low: 'var(--green)', Info: 'var(--green)' }
                    return (
                      <div key={i} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 13, padding: '18px 22px', display: 'flex', gap: 16, alignItems: 'flex-start', opacity: checked ? 0.6 : 1 }}>
                        <button onClick={() => setRoadmapChecked(prev => ({ ...prev, [i]: !checked }))}
                          style={{ width: 24, height: 24, borderRadius: '50%', border: `2px solid ${checked ? 'var(--green)' : 'var(--border)'}`, background: checked ? 'var(--green)' : 'transparent', cursor: 'pointer', flexShrink: 0, marginTop: 2, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 12, transition: 'all .2s' }}>
                          {checked ? '✓' : ''}
                        </button>
                        <div style={{ width: 28, height: 28, borderRadius: '50%', background: 'var(--surface2)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 0 }}>
                          <span style={{ fontFamily: 'Syne,sans-serif', fontWeight: 700, fontSize: 12, color: '#fff' }}>{i + 1}</span>
                        </div>
                        <div style={{ flex: 1 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                            <span style={{ fontFamily: 'Syne,sans-serif', fontSize: 14, fontWeight: 600, color: checked ? 'var(--ink2)' : 'var(--ink)', textDecoration: checked ? 'line-through' : 'none' }}>{step.title}</span>
                            <span style={{ fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 100, background: sevColors[step.sev], color: sevTextColors[step.sev] }}>{step.sev}</span>
                          </div>
                          <p style={{ fontSize: 13, color: 'var(--ink2)', lineHeight: 1.6, marginBottom: 8 }}>{step.desc}</p>
                          <span style={{ fontSize: 11, color: 'var(--ink2)', background: 'var(--cream)', padding: '2px 8px', borderRadius: 4 }}>⏱ {step.time}</span>
                        </div>
                        <button onClick={() => { setTab('assistant'); setTimeout(() => sendMessage(`Help me with this compliance task: ${step.title}. ${step.desc}`), 100) }}
                          style={{ fontSize: 11, padding: '6px 12px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0 }}>
                          Get help →
                        </button>
                      </div>
                    )
                  })}
                </div>
                <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 12, padding: '14px 20px', marginTop: 20, fontSize: 13, color: 'var(--ink2)' }}>
                  <strong style={{ color: 'var(--green)' }}>Tip:</strong> Check off each step as you complete it. Re-scan your site after making changes to see your score improve.
                </div>
              </div>
            )}

            {/* DOCUMENTS */}
            {tab === 'documents' && (
              <div>
                <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 6 }}>Compliance documents</h2>
                <p style={{ fontSize: 12, color: 'var(--ink2)', marginBottom: 20 }}>AI-generated and tailored for {result.url}</p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16, marginBottom: 20 }}>
                  {[
                    { key: 'privacy', name: 'Privacy Policy', icon: '📄', desc: 'Covers data collection, processing purposes, and user rights under GDPR Art. 13.' },
                    { key: 'cookie', name: 'Cookie Policy', icon: '🍪', desc: 'Full cookie table with all trackers found on your site, consent mechanism guidance.' },
                    { key: 'dpa', name: 'Data Processing Agreement', icon: '📋', desc: 'Template DPA for your third-party processors under GDPR Art. 28.' },
                  ].map(doc => (
                    <div key={doc.key} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: '22px 18px', display: 'flex', flexDirection: 'column' }}>
                      <div style={{ fontSize: 30, marginBottom: 14 }}>{doc.icon}</div>
                      <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, color: 'var(--ink)', marginBottom: 6 }}>{doc.name}</div>
                      <p style={{ fontSize: 12, color: 'var(--ink2)', lineHeight: 1.6, marginBottom: 18, flex: 1 }}>{doc.desc}</p>
                      {docState[doc.key] ? (
                        <div style={{ display: 'flex', gap: 8, flexDirection: 'column' }}>
                          <div style={{ background: '#F0FDF4', border: '1px solid var(--green-m)', borderRadius: 8, padding: '8px 12px', fontSize: 12, color: 'var(--green)', fontWeight: 500 }}>✅ Generated</div>
                          <button onClick={() => downloadText(docState[doc.key], `${doc.key}-policy-${result.url.replace(/[^a-z0-9]/gi, '-')}.txt`)}
                            style={{ width: '100%', padding: '9px', borderRadius: 8, border: 'none', background: 'var(--green)', color: '#fff', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}>
                            ⬇ Download
                          </button>
                          <button onClick={() => generateDocument(doc.key)}
                            style={{ width: '100%', padding: '7px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', fontSize: 11, cursor: 'pointer' }}>
                            ↺ Regenerate
                          </button>
                        </div>
                      ) : (
                        <button onClick={() => generateDocument(doc.key)} disabled={docLoading[doc.key]}
                          style={{ width: '100%', padding: '9px', borderRadius: 8, border: '1px solid var(--green-m)', background: docLoading[doc.key] ? 'var(--green-p)' : 'var(--green)', color: docLoading[doc.key] ? 'var(--green)' : '#fff', fontSize: 12, fontWeight: 500, cursor: docLoading[doc.key] ? 'default' : 'pointer' }}>
                          {docLoading[doc.key] ? '⏳ Generating...' : `Generate →`}
                        </button>
                      )}
                    </div>
                  ))}
                </div>
                {Object.values(docState).some(v => v) && (
                  <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: 22, marginBottom: 20 }}>
                    <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, marginBottom: 14 }}>Document preview</h3>
                    {Object.entries(docState).filter(([, v]) => v).map(([k, text]) => (
                      <div key={k} style={{ marginBottom: 16 }}>
                        <p style={{ fontSize: 12, fontWeight: 600, color: 'var(--green)', marginBottom: 8, textTransform: 'capitalize' }}>{k === 'dpa' ? 'Data Processing Agreement' : k === 'privacy' ? 'Privacy Policy' : 'Cookie Policy'}</p>
                        <pre style={{ fontSize: 12, color: 'var(--ink)', lineHeight: 1.7, whiteSpace: 'pre-wrap', wordBreak: 'break-word', background: 'var(--cream)', borderRadius: 8, padding: 16, maxHeight: 400, overflowY: 'auto', border: '1px solid var(--border)' }}>{text}</pre>
                      </div>
                    ))}
                  </div>
                )}
                <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 12, padding: '14px 20px', fontSize: 13, color: 'var(--ink2)' }}>
                  <strong style={{ color: 'var(--green)' }}>Disclaimer:</strong> All documents are AI-generated. They must be reviewed by a qualified solicitor before use. AlgoGrass does not provide legal advice.
                </div>
              </div>
            )}

            {/* AI ASSISTANT */}
            {tab === 'assistant' && (
              <div style={{ maxWidth: 680, margin: '0 auto' }}>
                <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 16, overflow: 'hidden' }}>
                  <div style={{ padding: '14px 20px', borderBottom: '1px solid var(--border)', background: 'var(--green-p)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, color: 'var(--green)' }}>🤖 AI Compliance Assistant</div>
                      <div style={{ fontSize: 11, color: 'var(--ink2)', marginTop: 2 }}>Powered by Claude · GDPR · UK DPA 2018 · ICO guidance</div>
                    </div>
                    <button onClick={() => setMessages([{ role: 'assistant', text: 'Hello! I am your AI compliance assistant. Ask me anything about GDPR, UK Data Protection Act 2018, cookie law, or data subject rights.' }])}
                      style={{ fontSize: 11, color: 'var(--ink2)', background: 'none', border: '1px solid var(--border)', borderRadius: 6, padding: '4px 10px', cursor: 'pointer' }}>Clear</button>
                  </div>
                  <div ref={chatRef} style={{ padding: '20px 22px', minHeight: 340, maxHeight: 420, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 14 }}>
                    {messages.map((m, i) => (
                      <div key={i} style={{ display: 'flex', justifyContent: m.role === 'user' ? 'flex-end' : 'flex-start' }}>
                        <div style={{ maxWidth: '82%', padding: '11px 15px', borderRadius: m.role === 'user' ? '16px 16px 4px 16px' : '16px 16px 16px 4px', background: m.role === 'user' ? 'var(--green)' : 'var(--green-p)', color: m.role === 'user' ? '#fff' : 'var(--ink)', fontSize: 13, lineHeight: 1.65, whiteSpace: 'pre-wrap' }}>{m.text}</div>
                      </div>
                    ))}
                    {aiLoading && <div style={{ display: 'flex' }}><div style={{ padding: '11px 15px', borderRadius: '16px 16px 16px 4px', background: 'var(--green-p)', fontSize: 13, color: 'var(--ink2)' }}>Thinking...</div></div>}
                  </div>
                  <div style={{ padding: '14px 22px', borderTop: '1px solid var(--border)', display: 'flex', gap: 9 }}>
                    <input className="field-input" placeholder="Ask about GDPR, cookies, data subject rights..." value={input} onChange={e => setInput(e.target.value)}
                      onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage() } }} disabled={aiLoading} style={{ flex: 1 }} />
                    <button onClick={() => sendMessage()} className="btn btn-primary" style={{ padding: '0 18px', minWidth: 48, fontSize: 17 }} disabled={aiLoading}>→</button>
                  </div>
                </div>
                <div style={{ marginTop: 12 }}>
                  <p style={{ fontSize: 12, color: 'var(--ink2)', marginBottom: 8 }}>Suggested questions:</p>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
                    {['What does GDPR require for a cookie banner?', 'How do I write a compliant privacy policy?', 'What is a lawful basis for data processing?', 'How do I handle a Subject Access Request?', 'What trackers need to be disclosed?'].map(q => (
                      <button key={q} onClick={() => sendMessage(q)}
                        style={{ fontSize: 11, padding: '6px 12px', borderRadius: 20, border: '1px solid var(--green-m)', background: 'var(--white)', color: 'var(--green)', cursor: 'pointer' }}
                        onMouseEnter={e => e.currentTarget.style.background = 'var(--green-p)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'var(--white)'}>
                        {q}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}
