'use client'
import { useState, useRef, useEffect, Suspense } from 'react'
import { useRouter } from 'next/navigation'

const HISTORY_KEY = 'algograss_scan_history'
const MAX_HISTORY = 10

function saveToHistory(result) {
  try {
    const prev = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]')
    const entry = { url: result.url, score: result.score, issueCount: result.issues.length, scannedAt: result.scannedAt }
    const filtered = prev.filter(h => h.url !== result.url)
    const updated = [entry, ...filtered].slice(0, MAX_HISTORY)
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated))
  } catch {}
}

function getHistory() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]') } catch { return [] }
}

function downloadText(text, filename) {
  const blob = new Blob([text], { type: 'text/plain' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
  URL.revokeObjectURL(a.href)
}

function buildReportText(result) {
  const lines = [
    `ALGOGRASS COMPLIANCE REPORT`,
    `===========================`,
    `Website: ${result.url}`,
    `Scanned: ${new Date(result.scannedAt).toLocaleString('en-GB')}`,
    `Compliance Score: ${result.score}/100`,
    ``,
    `SUMMARY`,
    `-------`,
    `HTTPS secure: ${result.isHttps ? 'Yes' : 'No'}`,
    `Trackers detected: ${result.trackers.length > 0 ? result.trackers.join(', ') : 'None'}`,
    `Issues found: ${result.issues.length}`,
    ``,
    `ISSUES`,
    `------`,
    ...(result.issues.length === 0
      ? ['No issues found — well done!']
      : result.issues.map((iss, i) => `${i + 1}. [${iss.sev}] ${iss.title}\n   ${iss.desc}\n   Regulation: ${iss.reg}`)),
    ``,
    `CHECKS`,
    `------`,
    ...Object.entries(result.checks).map(([k, v]) => `${k}: ${v ? 'PASS' : 'FAIL'}`),
    ``,
    `---`,
    `Generated by AlgoGrass · algograss.vercel.app`,
    `This report is for guidance only and does not constitute legal advice.`,
  ]
  return lines.join('\n')
}

export default function DashboardPage() {
  return <Suspense fallback={<div style={{ padding: 48, color: 'var(--ink2)' }}>Loading...</div>}><Dashboard /></Suspense>
}

function Dashboard() {
  const router = useRouter()
  const [tab, setTab] = useState('overview')
  const [scanUrl, setScanUrl] = useState('')
  const [scanning, setScanning] = useState(false)
  const [result, setResult] = useState(null)
  const [scanError, setScanError] = useState('')
  const [messages, setMessages] = useState([{ role: 'assistant', text: 'Hello! I am your AI compliance assistant. Ask me anything about GDPR, UK Data Protection Act 2018, cookie law, or data subject rights.' }])
  const [input, setInput] = useState('')
  const [aiLoading, setAiLoading] = useState(false)
  const [history, setHistory] = useState([])
  const [docState, setDocState] = useState({ privacy: null, cookie: null, dpa: null })
  const [docLoading, setDocLoading] = useState({ privacy: false, cookie: false, dpa: false })
  const chatRef = useRef(null)

  useEffect(() => { setHistory(getHistory()) }, [])
  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight }, [messages])

  async function runScan(url) {
    const target = url || scanUrl
    if (!target.trim()) return
    setScanning(true); setScanError(''); setResult(null); setTab('overview')
    setDocState({ privacy: null, cookie: null, dpa: null })
    try {
      const res = await fetch('/api/scan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: target.trim() }) })
      const data = await res.json()
      if (data.error) { setScanError(data.error); setScanning(false); return }
      setResult(data)
      saveToHistory(data)
      setHistory(getHistory())
    } catch { setScanError('Could not connect to scanner. Please check your connection.') }
    setScanning(false)
  }

  async function generateDocument(docType) {
    if (!result) return
    setDocLoading(prev => ({ ...prev, [docType]: true }))
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ docType, scanData: result }),
      })
      const data = await res.json()
      if (data.error) { alert('Error: ' + data.error); return }
      setDocState(prev => ({ ...prev, [docType]: data.document }))
    } catch { alert('Failed to generate document. Please try again.') }
    setDocLoading(prev => ({ ...prev, [docType]: false }))
  }

  async function sendMessage(text) {
    const q = (text || input).trim()
    if (!q || aiLoading) return
    setInput('')
    const history = [...messages, { role: 'user', text: q }]
    setMessages(history); setAiLoading(true)
    try {
      const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: history.map(m => ({ role: m.role, content: m.text })) }) })
      const data = await res.json()
      setMessages([...history, { role: 'assistant', text: data.reply || 'Something went wrong.' }])
    } catch { setMessages([...history, { role: 'assistant', text: 'Connection error. Please try again.' }]) }
    setAiLoading(false)
  }

  const scoreColor = result ? (result.score >= 70 ? 'var(--green)' : result.score >= 40 ? 'var(--amber-text)' : 'var(--red-text)') : 'var(--ink2)'
  const scoreLabel = result ? (result.score >= 70 ? 'Good' : result.score >= 40 ? 'Needs work' : 'At risk') : ''

  const tabs = [
    ['overview', 'Overview'],
    ['issues', result ? `Issues (${result.issues.length})` : 'Issues'],
    ['documents', 'Documents'],
    ['assistant', 'AI Assistant'],
    ['history', `History${history.length > 0 ? ` (${history.length})` : ''}`],
  ]

  return (
    <div style={{ minHeight: '100vh', background: '#F0F2F0' }}>
      {/* Header */}
      <div style={{ background: 'var(--ink)', padding: '22px 0' }}>
        <div className="wrap" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}>
          <div>
            <h1 style={{ fontFamily: 'Syne,sans-serif', fontSize: 20, fontWeight: 700, color: '#fff', marginBottom: 3 }}>Compliance Dashboard</h1>
            <p style={{ fontSize: 12, color: 'rgba(255,255,255,.45)' }}>
              {result ? `${result.url} · Scanned ${new Date(result.scannedAt).toLocaleString('en-GB')} · Score: ${result.score}/100` : 'Enter a website URL to run a real compliance scan'}
            </p>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            {result && (
              <button
                onClick={() => downloadText(buildReportText(result), `algograss-report-${result.url.replace(/[^a-z0-9]/gi, '-')}.txt`)}
                style={{ fontSize: 12, padding: '9px 14px', borderRadius: 8, border: '1px solid rgba(255,255,255,.25)', background: 'rgba(255,255,255,.1)', color: '#fff', cursor: 'pointer' }}
              >
                ⬇ Download Report
              </button>
            )}
            <form onSubmit={e => { e.preventDefault(); runScan() }} style={{ display: 'flex', gap: 8 }}>
              <input value={scanUrl} onChange={e => setScanUrl(e.target.value)} placeholder="yourwebsite.co.uk"
                style={{ background: 'rgba(255,255,255,.1)', border: '1px solid rgba(255,255,255,.2)', borderRadius: 8, padding: '9px 14px', fontSize: 13, color: '#fff', outline: 'none', width: 220 }} />
              <button type="submit" className="btn btn-primary btn-sm" disabled={scanning} style={{ minWidth: 100 }}>
                {scanning ? 'Scanning...' : '🔍 Run scan'}
              </button>
            </form>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div style={{ background: 'var(--white)', borderBottom: '1px solid var(--border)' }}>
        <div className="wrap" style={{ display: 'flex' }}>
          {tabs.map(([id, label]) => (
            <button key={id} onClick={() => setTab(id)} className={`tab ${tab === id ? 'on' : ''}`}>{label}</button>
          ))}
          <div style={{ flex: 1 }} />
          <button onClick={() => router.push('/')} style={{ fontSize: 12, color: 'var(--ink2)', background: 'none', border: 'none', cursor: 'pointer', padding: '0 16px' }}>← Back to site</button>
        </div>
      </div>

      <div className="wrap" style={{ padding: '32px 48px' }}>
        {/* Scanning spinner */}
        {scanning && (
          <div style={{ textAlign: 'center', padding: '64px 0' }}>
            <div style={{ width: 56, height: 56, border: '4px solid var(--green-p)', borderTop: '4px solid var(--green)', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 20px' }} />
            <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
            <p style={{ fontSize: 16, color: 'var(--ink2)', fontWeight: 300 }}>Scanning <strong style={{ color: 'var(--ink)', fontWeight: 500 }}>{scanUrl}</strong>...</p>
            <p style={{ fontSize: 12, color: 'var(--ink2)', marginTop: 8 }}>Checking HTTPS, cookies, trackers, privacy policy and more</p>
          </div>
        )}

        {/* Error */}
        {!scanning && scanError && (
          <div style={{ background: 'var(--red-bg)', border: '1px solid #F5B7B1', borderRadius: 14, padding: '24px 28px', maxWidth: 560 }}>
            <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 16, fontWeight: 600, color: 'var(--red-text)', marginBottom: 8 }}>Scan failed</h3>
            <p style={{ fontSize: 14, color: 'var(--red-text)', marginBottom: 16 }}>{scanError}</p>
            <button onClick={() => setScanError('')} className="btn btn-primary btn-sm">Try again</button>
          </div>
        )}

        {/* Empty state */}
        {!scanning && !scanError && !result && tab !== 'history' && (
          <div style={{ textAlign: 'center', padding: '64px 0' }}>
            <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'var(--green-p)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 32, margin: '0 auto 20px' }}>🔍</div>
            <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 22, fontWeight: 700, color: 'var(--ink)', marginBottom: 10 }}>No scan results yet</h2>
            <p style={{ fontSize: 15, color: 'var(--ink2)', marginBottom: 28, fontWeight: 300, maxWidth: 420, margin: '0 auto 28px' }}>Enter any website URL in the bar above and click Run scan to get real compliance results.</p>
            <div style={{ display: 'flex', gap: 8, justifyContent: 'center', flexWrap: 'wrap', maxWidth: 500, margin: '0 auto' }}>
              {['bbc.co.uk', 'tesco.com', 'amazon.co.uk', 'your-site.co.uk'].map(eg => (
                <button key={eg} onClick={() => { setScanUrl(eg); setTimeout(() => runScan(eg), 50) }}
                  style={{ fontSize: 12, padding: '7px 14px', borderRadius: 20, border: '1px solid var(--green-m)', background: 'var(--white)', color: 'var(--green)', cursor: 'pointer' }}>
                  Try {eg}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* ===================== HISTORY TAB ===================== */}
        {tab === 'history' && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
              <div>
                <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 3 }}>Scan history</h2>
                <p style={{ fontSize: 12, color: 'var(--ink2)' }}>Your last {MAX_HISTORY} scans · stored locally in this browser</p>
              </div>
              {history.length > 0 && (
                <button onClick={() => { localStorage.removeItem(HISTORY_KEY); setHistory([]) }}
                  style={{ fontSize: 12, padding: '7px 14px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--white)', color: 'var(--ink2)', cursor: 'pointer' }}>
                  Clear history
                </button>
              )}
            </div>
            {history.length === 0 ? (
              <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 14, padding: 28, textAlign: 'center' }}>
                <div style={{ fontSize: 40, marginBottom: 12 }}>📋</div>
                <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 16, fontWeight: 600, color: 'var(--green)', marginBottom: 8 }}>No history yet</h3>
                <p style={{ fontSize: 14, color: 'var(--ink2)' }}>Run a scan and it will appear here.</p>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {history.map((h, i) => {
                  const col = h.score >= 70 ? 'var(--green)' : h.score >= 40 ? 'var(--amber-text)' : 'var(--red-text)'
                  return (
                    <div key={i} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 13, padding: '16px 22px', display: 'flex', alignItems: 'center', gap: 20 }}>
                      <div style={{ width: 52, height: 52, borderRadius: '50%', background: 'var(--green-p)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                        <span style={{ fontFamily: 'Syne,sans-serif', fontWeight: 800, fontSize: 16, color: col }}>{h.score}</span>
                      </div>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--ink)', marginBottom: 3 }}>{h.url}</div>
                        <div style={{ fontSize: 12, color: 'var(--ink2)' }}>{h.issueCount} issue{h.issueCount !== 1 ? 's' : ''} · {new Date(h.scannedAt).toLocaleString('en-GB')}</div>
                      </div>
                      <button onClick={() => { setScanUrl(h.url); runScan(h.url); setTab('overview') }}
                        style={{ fontSize: 12, padding: '8px 15px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500 }}>
                        Re-scan →
                      </button>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        )}

        {/* ===================== RESULTS TABS ===================== */}
        {!scanning && !scanError && result && tab !== 'history' && (
          <>
            {/* ---- OVERVIEW ---- */}
            {tab === 'overview' && (
              <>
                {/* Score hero */}
                <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 16, padding: '28px 32px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 40 }}>
                  <div style={{ position: 'relative', width: 100, height: 100, flexShrink: 0 }}>
                    <svg viewBox="0 0 100 100" width="100" height="100">
                      <circle cx="50" cy="50" r="42" fill="none" stroke="var(--green-p)" strokeWidth="10" />
                      <circle cx="50" cy="50" r="42" fill="none" stroke={scoreColor} strokeWidth="10"
                        strokeDasharray={`${result.score * 2.64} 264`} strokeLinecap="round"
                        transform="rotate(-90 50 50)" />
                    </svg>
                    <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                      <span style={{ fontFamily: 'Syne,sans-serif', fontWeight: 800, fontSize: 22, color: scoreColor, lineHeight: 1 }}>{result.score}</span>
                      <span style={{ fontSize: 9, color: 'var(--ink2)', marginTop: 2 }}>/100</span>
                    </div>
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 22, fontWeight: 700, color: scoreColor, marginBottom: 4 }}>{scoreLabel}</div>
                    <div style={{ fontSize: 14, color: 'var(--ink2)', marginBottom: 12 }}>{result.url}</div>
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      <span style={{ fontSize: 12, padding: '4px 11px', borderRadius: 20, background: result.isHttps ? '#F0FDF4' : '#FEF2F2', color: result.isHttps ? 'var(--green)' : 'var(--red-text)', fontWeight: 500 }}>
                        {result.isHttps ? '🔒 HTTPS secure' : '⚠️ No HTTPS'}
                      </span>
                      <span style={{ fontSize: 12, padding: '4px 11px', borderRadius: 20, background: 'var(--green-p)', color: 'var(--green)', fontWeight: 500 }}>
                        {result.issues.length} issue{result.issues.length !== 1 ? 's' : ''} found
                      </span>
                      {result.trackers.length > 0 && (
                        <span style={{ fontSize: 12, padding: '4px 11px', borderRadius: 20, background: 'var(--amber-bg)', color: 'var(--amber-text)', fontWeight: 500 }}>
                          📡 {result.trackers.length} tracker{result.trackers.length !== 1 ? 's' : ''}
                        </span>
                      )}
                    </div>
                  </div>
                  <button onClick={() => downloadText(buildReportText(result), `algograss-report-${result.url.replace(/[^a-z0-9]/gi, '-')}.txt`)}
                    style={{ fontSize: 13, padding: '10px 18px', borderRadius: 9, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500, whiteSpace: 'nowrap', flexShrink: 0 }}>
                    ⬇ Download Report
                  </button>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 14, marginBottom: 24 }}>
                  {[
                    ['Compliance score', result.score + '/100', scoreColor],
                    ['Issues found', result.issues.length + ' total', result.issues.length > 0 ? 'var(--red-text)' : 'var(--green)'],
                    ['Trackers detected', result.trackers.length + ' found', result.trackers.length > 0 ? 'var(--amber-text)' : 'var(--green)'],
                    ['HTTPS secure', result.isHttps ? 'Yes' : 'No', result.isHttps ? 'var(--green)' : 'var(--red-text)'],
                  ].map(([label, val, col]) => (
                    <div key={label} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: '18px 16px' }}>
                      <div style={{ fontSize: 10, color: 'var(--ink2)', textTransform: 'uppercase', letterSpacing: '.08em', fontWeight: 600, marginBottom: 7 }}>{label}</div>
                      <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 28, fontWeight: 800, color: col, lineHeight: 1 }}>{val}</div>
                    </div>
                  ))}
                </div>

                {result.trackers.length > 0 && (
                  <div style={{ background: 'var(--amber-bg)', border: '1px solid #F0C070', borderRadius: 12, padding: '12px 18px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 12 }}>
                    <span style={{ fontSize: 18 }}>📡</span>
                    <div>
                      <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--amber-text)' }}>Trackers detected: </span>
                      <span style={{ fontSize: 13, color: 'var(--amber-text)' }}>{result.trackers.join(', ')}</span>
                      <span style={{ fontSize: 12, color: 'var(--amber-text)', marginLeft: 8, opacity: .8 }}>— must be disclosed in your privacy policy</span>
                    </div>
                  </div>
                )}

                <div style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gap: 20 }}>
                  <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: 22 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                      <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600 }}>{result.issues.length === 0 ? '🎉 No issues found!' : 'Top issues to fix'}</h3>
                      {result.issues.length > 3 && <button onClick={() => setTab('issues')} style={{ fontSize: 12, color: 'var(--green)', background: 'none', border: 'none', cursor: 'pointer' }}>View all →</button>}
                    </div>
                    {result.issues.length === 0
                      ? <p style={{ fontSize: 14, color: 'var(--green)', fontWeight: 500 }}>This website passed all our compliance checks.</p>
                      : result.issues.slice(0, 3).map((iss, i) => (
                        <div key={i} style={{ display: 'flex', gap: 10, padding: '11px 0', borderBottom: '1px solid var(--green-p)', alignItems: 'flex-start' }}>
                          <span className={`chip chip-${iss.sev.toLowerCase()}`} style={{ marginTop: 2, flexShrink: 0 }}>{iss.sev}</span>
                          <div style={{ flex: 1 }}>
                            <div style={{ fontSize: 13, fontWeight: 500, color: 'var(--ink)', marginBottom: 2 }}>{iss.title}</div>
                            <div style={{ fontSize: 11, color: 'var(--ink2)' }}>{iss.reg}</div>
                          </div>
                          <button onClick={() => { setTab('assistant'); setTimeout(() => sendMessage(`How do I fix: ${iss.title}?`), 100) }}
                            style={{ fontSize: 11, padding: '5px 11px', borderRadius: 6, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', whiteSpace: 'nowrap' }}>
                            Get help
                          </button>
                        </div>
                      ))}
                  </div>
                  <div style={{ background: 'var(--green)', borderRadius: 14, padding: 22 }}>
                    <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, color: '#fff', marginBottom: 14 }}>Quick actions</h3>
                    {[
                      ['View all issues', '⚠️', () => setTab('issues')],
                      ['Generate Privacy Policy', '📄', () => { setTab('documents'); setTimeout(() => generateDocument('privacy'), 200) }],
                      ['Generate Cookie Policy', '🍪', () => { setTab('documents'); setTimeout(() => generateDocument('cookie'), 200) }],
                      ['Generate DPA', '📋', () => { setTab('documents'); setTimeout(() => generateDocument('dpa'), 200) }],
                      ['Ask AI assistant', '🤖', () => setTab('assistant')],
                    ].map(([label, icon, action]) => (
                      <button key={label} onClick={action}
                        style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 9, padding: '10px 13px', borderRadius: 9, border: '1px solid rgba(255,255,255,.15)', background: 'rgba(255,255,255,.08)', color: '#fff', fontSize: 13, cursor: 'pointer', marginBottom: 7, textAlign: 'left', transition: 'background .2s' }}
                        onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,.18)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,.08)'}>
                        <span>{icon}</span>{label}
                      </button>
                    ))}
                  </div>
                </div>
              </>
            )}

            {/* ---- ISSUES ---- */}
            {tab === 'issues' && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                  <div>
                    <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 3 }}>All issues for {result.url}</h2>
                    <p style={{ fontSize: 12, color: 'var(--ink2)' }}>{result.issues.length} total</p>
                  </div>
                  <button onClick={() => setTab('assistant')} className="btn btn-primary btn-sm">Get AI help</button>
                </div>
                {result.issues.length === 0 ? (
                  <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 14, padding: 28, textAlign: 'center' }}>
                    <div style={{ fontSize: 40, marginBottom: 12 }}>🎉</div>
                    <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, color: 'var(--green)', marginBottom: 8 }}>No issues detected</h3>
                    <p style={{ fontSize: 14, color: 'var(--ink2)' }}>This website passed all our automated compliance checks.</p>
                  </div>
                ) : (
                  <>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 20 }}>
                      {result.issues.map((iss, i) => (
                        <div key={i} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 13, padding: '18px 22px', display: 'grid', gridTemplateColumns: '80px 1fr auto', gap: 14, alignItems: 'start' }}>
                          <span className={`chip chip-${iss.sev.toLowerCase()}`} style={{ textAlign: 'center', display: 'block', padding: '4px 0', borderRadius: 6, fontSize: 11 }}>{iss.sev}</span>
                          <div>
                            <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--ink)', marginBottom: 5 }}>{iss.title}</div>
                            <div style={{ fontSize: 12, color: 'var(--ink2)', lineHeight: 1.55, marginBottom: 7 }}>{iss.desc}</div>
                            <span style={{ fontSize: 10, background: 'var(--green-p)', color: 'var(--green)', padding: '2px 8px', borderRadius: 4 }}>{iss.reg}</span>
                          </div>
                          <button onClick={() => { setTab('assistant'); setTimeout(() => sendMessage(`How do I fix: ${iss.title}? The regulation is ${iss.reg}.`), 100) }}
                            style={{ fontSize: 12, padding: '8px 15px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer', fontWeight: 500, whiteSpace: 'nowrap' }}>
                            Fix with AI →
                          </button>
                        </div>
                      ))}
                    </div>
                    <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: 22 }}>
                      <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, marginBottom: 16 }}>Full check summary</h3>
                      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 2 }}>
                        {Object.entries({
                          'HTTPS encryption': result.checks.https,
                          'Privacy policy': result.checks.privacyPolicy,
                          'Cookie banner': result.checks.cookieBanner,
                          'Cookie reject option': result.checks.cookieReject,
                          'Terms of service': result.checks.termsOfService,
                          'Lawful basis stated': result.checks.lawfulBasis,
                          'Data subject rights': result.checks.dataRights,
                          'Trackers disclosed': result.checks.trackersDisclosed,
                          'Retention period stated': result.checks.retentionPolicy,
                          'DSAR contact present': result.checks.dsarContact,
                          'DPO mentioned': result.checks.dpo,
                          'Subprocessors listed': result.checks.subprocessorsList,
                        }).map(([label, passed]) => (
                          <div key={label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '11px 16px', background: passed ? '#F0FDF4' : '#FEF2F2', borderRadius: 8, margin: 2 }}>
                            <span style={{ fontSize: 13, color: 'var(--ink)' }}>{label}</span>
                            <span style={{ fontSize: 15 }}>{passed ? '✅' : '❌'}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </>
                )}
              </div>
            )}

            {/* ---- DOCUMENTS ---- */}
            {tab === 'documents' && (
              <div>
                <h2 style={{ fontFamily: 'Syne,sans-serif', fontSize: 18, fontWeight: 600, marginBottom: 6 }}>Compliance documents</h2>
                <p style={{ fontSize: 12, color: 'var(--ink2)', marginBottom: 20 }}>Tailored for {result.url} · AI-generated using your scan data</p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16, marginBottom: 20 }}>
                  {[
                    { key: 'privacy', name: 'Privacy Policy', icon: '📄', desc: 'Covers your data collection, processing purposes, and user rights under GDPR Art. 13.' },
                    { key: 'cookie', name: 'Cookie Policy', icon: '🍪', desc: 'Documents the cookies and trackers found on your site with a full cookie table.' },
                    { key: 'dpa', name: 'Data Processing Agreement', icon: '📋', desc: 'Template DPA for your third-party processors under GDPR Art. 28.' },
                  ].map(doc => (
                    <div key={doc.key} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: '22px 18px', display: 'flex', flexDirection: 'column' }}>
                      <div style={{ fontSize: 30, marginBottom: 14 }}>{doc.icon}</div>
                      <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, color: 'var(--ink)', marginBottom: 6 }}>{doc.name}</div>
                      <p style={{ fontSize: 12, color: 'var(--ink2)', lineHeight: 1.6, marginBottom: 18, flex: 1 }}>{doc.desc}</p>
                      {docState[doc.key] ? (
                        <div style={{ display: 'flex', gap: 8, flexDirection: 'column' }}>
                          <div style={{ background: '#F0FDF4', border: '1px solid var(--green-m)', borderRadius: 8, padding: '8px 12px', fontSize: 12, color: 'var(--green)', fontWeight: 500 }}>✅ Generated successfully</div>
                          <button
                            onClick={() => downloadText(docState[doc.key], `${doc.key}-policy-${result.url.replace(/[^a-z0-9]/gi, '-')}.txt`)}
                            style={{ width: '100%', padding: '9px', borderRadius: 8, border: 'none', background: 'var(--green)', color: '#fff', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}>
                            ⬇ Download {doc.name}
                          </button>
                          <button
                            onClick={() => generateDocument(doc.key)}
                            style={{ width: '100%', padding: '7px', borderRadius: 8, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', fontSize: 11, fontWeight: 500, cursor: 'pointer' }}>
                            ↺ Regenerate
                          </button>
                        </div>
                      ) : (
                        <button
                          onClick={() => generateDocument(doc.key)}
                          disabled={docLoading[doc.key]}
                          style={{ width: '100%', padding: '9px', borderRadius: 8, border: '1px solid var(--green-m)', background: docLoading[doc.key] ? 'var(--green-p)' : 'var(--green)', color: docLoading[doc.key] ? 'var(--green)' : '#fff', fontSize: 12, fontWeight: 500, cursor: docLoading[doc.key] ? 'default' : 'pointer' }}>
                          {docLoading[doc.key] ? '⏳ Generating...' : `Generate ${doc.name} →`}
                        </button>
                      )}
                    </div>
                  ))}
                </div>

                {/* Preview area */}
                {Object.entries(docState).some(([, v]) => v) && (
                  <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 14, padding: 22, marginBottom: 20 }}>
                    <h3 style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, marginBottom: 14 }}>Document preview</h3>
                    <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
                      {[['privacy', '📄 Privacy Policy'], ['cookie', '🍪 Cookie Policy'], ['dpa', '📋 DPA']].map(([k, label]) => docState[k] && (
                        <button key={k} onClick={() => setTab('documents')}
                          style={{ fontSize: 12, padding: '6px 14px', borderRadius: 20, border: '1px solid var(--green-m)', background: 'var(--green-p)', color: 'var(--green)', cursor: 'pointer' }}>
                          {label}
                        </button>
                      ))}
                    </div>
                    {Object.entries(docState).filter(([, v]) => v).map(([k, text]) => (
                      <div key={k} style={{ marginBottom: 16 }}>
                        <pre style={{ fontSize: 12, color: 'var(--ink)', lineHeight: 1.7, whiteSpace: 'pre-wrap', wordBreak: 'break-word', background: 'var(--cream)', borderRadius: 8, padding: 16, maxHeight: 400, overflowY: 'auto', border: '1px solid var(--border)' }}>
                          {text}
                        </pre>
                      </div>
                    ))}
                  </div>
                )}

                <div style={{ background: 'var(--green-p)', border: '1px solid var(--green-m)', borderRadius: 12, padding: '16px 20px', fontSize: 13, color: 'var(--ink2)', lineHeight: 1.65 }}>
                  <strong style={{ color: 'var(--green)' }}>Disclaimer:</strong> All documents are AI-generated based on your scan. They must be reviewed by a qualified solicitor before use. AlgoGrass does not provide legal advice.
                </div>
              </div>
            )}

            {/* ---- AI ASSISTANT ---- */}
            {tab === 'assistant' && (
              <div style={{ maxWidth: 680, margin: '0 auto' }}>
                <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 16, overflow: 'hidden' }}>
                  <div style={{ padding: '16px 22px', borderBottom: '1px solid var(--border)', background: 'var(--green-p)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 15, fontWeight: 600, color: 'var(--green)' }}>🤖 AI Compliance Assistant</div>
                      <div style={{ fontSize: 11, color: 'var(--ink2)', marginTop: 2 }}>Powered by Claude · GDPR · UK DPA 2018 · ICO guidance</div>
                    </div>
                    <button onClick={() => setMessages([{ role: 'assistant', text: 'Hello! I am your AI compliance assistant. Ask me anything about GDPR, UK Data Protection Act 2018, cookie law, or data subject rights.' }])}
                      style={{ fontSize: 11, color: 'var(--ink2)', background: 'none', border: '1px solid var(--border)', borderRadius: 6, padding: '4px 10px', cursor: 'pointer' }}>
                      Clear chat
                    </button>
                  </div>
                  <div ref={chatRef} style={{ padding: '20px 22px', minHeight: 340, maxHeight: 420, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 14 }}>
                    {messages.map((m, i) => (
                      <div key={i} style={{ display: 'flex', justifyContent: m.role === 'user' ? 'flex-end' : 'flex-start' }}>
                        <div style={{ maxWidth: '82%', padding: '11px 15px', borderRadius: m.role === 'user' ? '16px 16px 4px 16px' : '16px 16px 16px 4px', background: m.role === 'user' ? 'var(--green)' : 'var(--green-p)', color: m.role === 'user' ? '#fff' : 'var(--ink)', fontSize: 13, lineHeight: 1.65, whiteSpace: 'pre-wrap' }}>
                          {m.text}
                        </div>
                      </div>
                    ))}
                    {aiLoading && <div style={{ display: 'flex' }}><div style={{ padding: '11px 15px', borderRadius: '16px 16px 16px 4px', background: 'var(--green-p)', fontSize: 13, color: 'var(--ink2)' }}>Thinking...</div></div>}
                  </div>
                  <div style={{ padding: '14px 22px', borderTop: '1px solid var(--border)', display: 'flex', gap: 9 }}>
                    <input className="field-input" placeholder="Ask about GDPR, cookies, data subject rights..." value={input} onChange={e => setInput(e.target.value)}
                      onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage() } }} disabled={aiLoading} style={{ flex: 1 }} />
                    <button onClick={() => sendMessage()} className="btn btn-primary" style={{ padding: '0 18px', minWidth: 48, fontSize: 17 }} disabled={aiLoading}>→</button>
                  </div>
                </div>
                <div style={{ marginTop: 12 }}>
                  <p style={{ fontSize: 12, color: 'var(--ink2)', marginBottom: 8 }}>Suggested questions:</p>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
                    {['What does GDPR require for a cookie banner?', 'How do I write a compliant privacy policy?', 'What is a lawful basis for data processing?', 'How do I handle a data subject access request?'].map(q => (
                      <button key={q} onClick={() => sendMessage(q)}
                        style={{ fontSize: 11, padding: '6px 12px', borderRadius: 20, border: '1px solid var(--green-m)', background: 'var(--white)', color: 'var(--green)', cursor: 'pointer' }}
                        onMouseEnter={e => e.currentTarget.style.background = 'var(--green-p)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'var(--white)'}>
                        {q}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}
